tokenizer:
  inputCol: 'reviewText'
  outputCol: 'reviews_vector'
stopwords:
  inputCol: 'reviews_vector'
  outputCol: 'reviews_filtered'
vectorizer:
  inputCol: 'reviews_filtered'
  outputCol: 'features'